# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1343091760fa52bf06c9edb85bbb22ab18c6f2fe9092eb3968c213178c7da8e30f494d00378c3389b3e91a10a711320bb84f07141c796c6bbc853321c3326ad

test:
  secret_key_base: 5070e220d05db6cd675575cbb8aae4db42937cf37ea6d5d7df89b4bba0a284758811a962684945d9ea2ccd33160e081c96fd5c6faaf2ebf7c4fb5c6a0409077f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
